// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/1/2025, 11:08:44 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/apple/Yellow/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/apple/Yellow/src/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/apple/Yellow/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/apple/Yellow/src/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/apple/Yellow/src/plugins/**/*.{js,ts,mjs}","/Users/apple/Yellow/src/composables/**/*.{js,ts,mjs}","/Users/apple/Yellow/src/utils/**/*.{js,ts,mjs}","/Users/apple/Yellow/src/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/apple/Yellow/src/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/apple/Yellow/src/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/apple/Yellow/src/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["content"]["files"]["12"] = "/Users/apple/Yellow/src/config/formkit.config.js";;return cfg;})();

export default resolvedConfig;